from collections import deque
from datetime import datetime


class XAIReportArchive:
    # archive that stores the explanations generated by ML models
    archive = deque(maxlen=100)

    @classmethod
    def save_mlengine_explanation(cls, client_id, risk_score, explanation):
        # function saves the basic forensics as of right now. Will be expanded upon later
        cls.archive.appendleft({
            "timestamp": str(datetime.now()),
            "client_id": client_id,
            "risk_score": risk_score,
            "explanation": explanation
        })